# Generated by Django 3.1.4 on 2020-12-16 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querysets', '0002_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='querysets.car'),
        ),
    ]
