# Generated by Django 3.1.4 on 2020-12-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querysets', '0003_auto_20201216_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car',
            new_name='cars',
        ),
    ]
